### ISSUE TITLE
Create credit card payment does not work

### ISSUE THREAD

**Issue by jvanoosterom** [stil4m/mollie-api#10]
when creating an payment other than iDeal: eg CreditCard
the optional return values are different  (getPayment ApI)
The field 'details' is an Object in that case instead of a String

**Comment by stil4m** [comment]
Thanks for the report. I'll look into it. If you want/can, you can create a PR with the appropriate test.

**Comment by jvanoosterom** [comment]
fix seams to be to change the field 'details' in CreatedPayment 
to type `Map<String,Object>` which will be null if iDeal and filled if there are optional details

**Comment by stil4m** [comment]
Ok. You can change it if you want and run the test to verify if nothing breaks. I'll will release it as a 2.0.0 version since it will be a breaking API change.

Kinda strange because the `details` field seems to be an undocumented feature :p : [https://www.mollie.com/nl/docs/reference/payments/create](https://www.mollie.com/nl/docs/reference/payments/create)

**Comment by jvanoosterom** [comment]
the result of create payment is a payment and a payment is documented here:
https://www.mollie.com/nl/docs/reference/payments/get

**Comment by stil4m** [comment]
Seems legit!

**Comment by stil4m** [comment]
Just released 2.0.0. Thanks for your contribution!
