### ISSUE TITLE
Add the webhookUrl parameter to payments

### ISSUE THREAD

**Issue by jcassee** [stil4m/mollie-api#15]

**Comment by jcassee** [comment]
Both #16 and #17 are implementations for this feature. (I have a preference for #17.)

@stil4m Do either of these implementations make sense?

**Comment by stil4m** [comment]
Both implementations make sense. I prefer #16 because it will handle `webhookUrl` as real property and as you have mentioned supports the immutability of the POJO. I will make some comments and then it would be ready to merge.
That said, this choice will require more changes in the future (for new properties), but I like to keep things explicit.
