### ISSUE TITLE
Unrecognized field "resource" (class nl.stil4m.mollie.domain.Payment)

### ISSUE THREAD

**Issue by tubbynl** [stil4m/mollie-api#23]
it seems the Payment rest resource in some (not yet predictable) scenario's returns a resource property. When this happened on my testruns/builds retriggering helped :s 

Obviously we don't want the tests to be a russian roulette; this ticket is a placeholder, i'll first mail mollie with this perhaps they will fix it or else we need to ignore this or make it an optional property. This property is not mentioned in the docs of mollie
https://www.mollie.com/nl/docs/reference/payments/get

testNextPayments(nl.stil4m.mollie.DynamicClientIntegrationTest)  Time elapsed: 2.496 sec  <<< ERROR!
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "resource" (class nl.stil4m.mollie.domain.Payment), not marked as ignorable (18 known properties: "expiredDatetime", "method", "details", "mode", "profileId", "paidDatetime", "cancelledDatetime", "amountRefunded", "status", "expiryPeriod", "amount", "links", "locale", "id", "description", "amountRemaining", "createdDatetime", "metadata"])
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@115667d; line: 1, column: 2657](through reference chain: nl.stil4m.mollie.domain.Page["data"]->java.util.ArrayList[5]->nl.stil4m.mollie.domain.Payment["resource"])

**Comment by stil4m** [comment]
I've seen that they have added 'resource' to some of the entities. My guess: `resource` will be added to payments that are created via the endpoint `/customers/x/payments`. Because the tests on #19 are run, these payments come up in the `GET /payments` endpoint (in another branch).
#19 fixes this by adding `resource` to the `Payment` POJO.

But still the problem is at mollie, because `resource` is not documented at [https://www.mollie.com/en/docs/reference/payments/get](https://www.mollie.com/en/docs/reference/payments/get).

**Comment by stil4m** [comment]
PS: Merging the `feature/issue-19` branch would fix everything. @tubbynl You reviewed the code already. You think it is ok?

**Comment by tubbynl** [comment]
i'll pull in the latest and will review it right away

**Comment by tubbynl** [comment]
their response btw;

> Is dit bij het ophalen van een Payment? Want ik weet wel dat hij bij een Customer zit: https://www.mollie.com/nl/docs/reference/customers/get

**Comment by tubbynl** [comment]
i think it's ok; perhaps some improvements
- splitting tests  (Dynamic)ClientIntegrationTest into own tests into own tests inside concepts
- configuring jackson to json deserialize more forgiving (ignore unknown props) in order to be more robust

the first i can do some work on the second is more of a discussion on whether that's a good thing to want

**Comment by stil4m** [comment]
Related to their response: Yes this is when fetching the payments through `/payments`.

I have created two issues #24 and #25 for what you have mentioned. I see these as improvements not necessities to make the API work. There is a workaround for the deserialization by injecting an ObjectMapper.

**Comment by stil4m** [comment]
I will merge the issue-19 later this day. I'm at work and I still have to do something :p

**Comment by tubbynl** [comment]
sorry for that :)

in my current project i'll be using the recurring payments part so i'm happy do some of the other work/issues on this

**Comment by Daanvm** [comment]
You're right @stil4m, the `resource` attribute is only added for payments which have an API customer. We wanted to make the endpoints more consistent by adding the `resource` attribute to each response. We didn't want to break existing implementations, so that's why wo only added it to payments with a customer.

I can imagine it's confusing the way it's right now. I'll report it internally, we can at least update the docs.

Further would I recommend ignoring unknown fields from our API. We might occasionally [add new fields](https://www.mollie.com/en/docs/changelog), for example to the payment details object for new payment types. Note that it will never be backwards incompatible when you ignore the unknown fields.

**Comment by tubbynl** [comment]
yep, we are aware of your last statement and are considering that in #25

**Comment by stil4m** [comment]
HI Daanvm,

I understand that you guys didn't want to break the existing implementations, no problem. I was just wondering why the resource property is there at all? When I fetch payment, I expect payments. Are there endpoints that return mixed content? I ask this due to some architectural decisions that I might make if that is the case.
