### ISSUE TITLE
Suggestion for new Java API

### ISSUE THREAD

**Issue by jcassee** [stil4m/mollie-api#31]
This is my suggestion for a more extensible Java API for Mollie. It is fleshed out enough to convey the ideas:

https://github.com/jcassee/mollie-api/tree/experimental

Some decisions / highlights:
* Fluent API.
* Attempt at separation between construction of request entities, construction of requests and execution of requests.
* Adds `Iterator` for lists of entities, guaranteed to return all items once, even when items are added during iteration.
* Use as few runtime dependencies as possible.
* Annotations and parameter checks for defends against `NullPointerException`s. [No `Optional` parameters](http://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555).
  * Methods accept null parameters by default but return non-null values by default.
* Organization based on API modules.
* Expects API calls to succeed.
* Javadoc based on Mollie documentation. (See `payments` package.)
* Works even if the Mollie API changes.
* Real tests that check request and response JSON.
* Non-configurable `ObjectMapper` to guarantee API compatibility.
* Uses `Pojomatic` for `equals`, `hashCode` and `toString`.
* Purely visual, to seduce the Mollie guys to take it on as an official library: use `nl.mollie` package. :smile:

Problems:
* ~~Due to the combination of `LocalServerTestBase` and OpenJDK 8 you need the Sun JDK. This must be fixed.~~

I am really interested in your opinion, @stil4m!

**Comment by stil4m** [comment]
Just got home and two busy days ahead. Probably Saturday until I take a good look at it.

**Comment by jcassee** [comment]
No problem! I'll try and fix the problem with OpenJDK and then let it rest for you to take a look at.

**Comment by jcassee** [comment]
Okay, the the OpenJDK thing was a configuration error on my side. (Briefly, I installed an Ubuntu package that went out of its way to select Java 9...)

**Comment by tubbynl** [comment]
this is not only a new API it's also a new implementation ;) aka breaking current usage of this library
- i do agree that the fluent api would be nice and it could dry-up some of the plumping in Concepts/Clients
- its not reducing the runtime dependencies (only adding pojomatic)
- renaming the package and stuff is more something for #21
- unit tests testing to and from json is a good thing to have

gut feeling on my side says it's a good direction but i would re-do it in incremental commits and prehaps provide (deprecated)implementations for current API (nice-to-have). And if we want this better sooner than later.

**Comment by jcassee** [comment]
@tubbynl Fair points. I had already remarked that it would be a whole new API and have a different "style" in #19. @stil4m Did you find the time to look at it? I am using the code in one of my projects (because of #38).

**Comment by stil4m** [comment]
Tonight or tomorrow

**Comment by stil4m** [comment]
I've read through the source code and in general I think it is an improvement. Somethings make the library much better, such as the docs, use of AssertJ and Pojomatic. Somethings I personally do not like, such as the removal of the Optionals, expects API calls to succeed and the suppression of warnings, but later more on this. 

My vision on this API is:
- This library should be developer friendly. Not resulting in errors that you can only find when you actually know the source.
- This library should be a reflection on the actual API that Mollie provides. Nothing more and nothing less.

**Fluent API**  
I like the Fluent API, but not as core. My biggest concern is that people will forget arguments, make mistakes due to the mutability (people will pass the fluent objects around, which will lead to bugs). I see the pro that there will be less breaking api changes because constructors will be changed.

The problem what developers can do with the new API is:

```
x = PaymentRequest.creditCard()
    .amount(1.00)

// Send x to mollie
```

Which we know is definitely not good. In combination with the 'expects API calls to succeed', I do not think this is a stable foundation.

**Attempt at separation between construction of request entities, construction of requests and execution of requests.**  

I do not see how this is differently set up as the current API.

**Adds Iterator for lists of entities, guaranteed to return all items once, even when items are added during iteration.**

I do like this improvement, its a nice to have. But I am not sure if it belongs in the API. If you want to iterate over all entities, fetch them. It's not really iterating over all the entities, because you might miss one. Due to the missing soundness, I favour in leaving this functionality out.

**Annotations and parameter checks for defends against NullPointerExceptions**

I have read the post and I see the reason why you would remove the optional arguments. I agree that removing the `Optional` parameters will make the API more cleaner, by changing them into `nullable`s.

**Organisation based on API modules.**

This is already the case. I see no significant change in this.

**Expects API calls to succeed.**

See my first point of the 'vision'. I do not agree on this. I believe an API client should limit the calls on the actual API when failures can be detected prior to the request. This is currently not covered in the implementation, but was covered in the original (with the verbose constructors).

**Javadoc based on Mollie documentation. (See payments package.)**

+9000

**Works even if the Mollie API changes.**

Depends on the change. With https://github.com/stil4m/mollie-api/issues/25 this is already covered. I believe the when Mollie makes a breaking change we should notify them making them get their act together: If you provide a public API, and you even include version numbers in your URI, you should not make breaking changes. This 'breakability' of this library is a reflection of their quality, and although that makes me sad, I think it should remain like this.
How does this implementation resolve more issues than what is covered in #25?

**Real tests that check request and response JSON**

Very good addition. Will improve the stability significantly.

**Non-configurable ObjectMapper to guarantee API compatibility.**

I do not agree on this change see #25 and my previous comment in #19:

> Currently the default ObjectMapper makes use of the Jdk8Module to be able map Optional and DateTime. Suppose Java 9 comes out, people will be able to inject an ObjectMapper with a Jdk9Module. In addition users of the library may embed their own domain objects in the meta data of a payment. As well for this they may want to inject an ObjectMapper with custom encoding/decoding functionality.

**Uses Pojomatic for equals, hashCode and toString.**

Good addition.

**Purely visual, to seduce the Mollie guys to take it on as an official library: use nl.mollie package.**

Can't do this. I do not work at mollie and I think it is (legally) not allowed to publish under their name.

---

To conclude, I think there are a lot of good additions in your patch. I do not agree on all the points, because I think it violates my believes of what this library should and should not be. Maybe I need some more convincing. I see your arguments of these changes, but maybe I miss the 'why'. As a developer you have concerns with what a library should do for your domain. I've used this library in 3 different projects and all have different problems. These problems thrive a solution. So I think I need to know more about the problems you are facing to commit to a solution. I do like this input, because it will broaden my view as well. As @tubbynl mentioned, I would like to see incremental changes with the improvements. But that is maybe a thing when the solution is more crystallised. 

Yesterday I have merged two PR's. I will release these as `2.3.0` later this day.

**Comment by jcassee** [comment]
Thanks, @tubbynl and @stil4m for the responses. Let me respond to Mats' message, as Michaël's points are in there too, I think.

**Fluent API**

You have two concerns here:
1. _Request objects will be passed around._ The canonical mistake here, I guess, would be passing a partly-constructed object to a method that adds properties, after which object is also changed for the callee. I have never used an API where the request objects escape from the method that does the API call. These are not domain entities, I think. Do you have an example?
2. _It is possible to construct invalid requests._ I actually think that this is a feature. For example, before recurring payments, `redirectUrl` was required. I personally dislike a client library that think it knows better than me. Also, it is pretty simple to add an `isValid` method to the entities that is checked before doing the request.

**Attempt at separation between construction of request entities, construction of requests and execution of requests.**

Agree, this is not different from the current API. I had been experimenting with an API that was even more fluent and that had the request itself call the request:

`Payment p = PaymentRequest.creditcard().amount(10).description("New bike").call()`

**Adds Iterator for lists of entities, guaranteed to return all items once, even when items are added during iteration.**

You write that "It's not really iterating over all the entities, because you might miss one." I think I might be missing something. When an item is added during paging, you run the risk of visiting the same item twice. I don't see how you could miss one.

I think getting all _X_'s (payments, methods, etc.) is something many clients will want to do. The iterator protects against duplicate results. The code is a bit tricky, which is why I think including it would be great.

**Organisation based on API modules.**

The only significant change is removing the domain layer and adding those classes to the module package. The cohesion within the module package is stronger, I think. This makes it possible to simplify code by using package visibility between the request entities and modules.

**Expects API calls to succeed.**

Can you explain why it is important not to go to the API? I do not believe a client library can predict 100% whether a call will succeed or not (especially with a developing API like Mollie). What is the harm in leaving error handling to the API?

**Works even if the Mollie API changes.**

The main thing is that you can set request properties and get response properties that the library author has not included (`ExtensibleEntity.get` and `.set`). So if Mollie adds something and the library is not updated you can still get at the new information. (It is much more difficult to fork a Java project, publish it and use that version temporarily than, say, an NPM package.)

**Non-configurable ObjectMapper to guarantee API compatibility.**

You want to allow users to use their own encoding and add for example the JDK9 Jackson module. However, this can also cause the client to break in weird ways, for example if the ObjectMapper is configured to encode timestamps as Numbers (Unix timestamp) instead of ISO 8601 strings. Additionally, I think it is better to force users of the client to convert their types to something close to the JSON types. (Timestamps are a grey area here, in my opinion.) Otherwise, the error messages occur in the (de)serialization layer where they are more difficult to debug.

 **Purely visual, to seduce the Mollie guys to take it on as an official library: use nl.mollie package.**

Yeah, this was meant as a joke. I was duplicating code and needed a new package name...

That leaves one remark from Michaël: **its not reducing the runtime dependencies (only adding pojomatic)**

Indeed, this is a principle that I retained from the original code. I had initially _increased_ the number of runtime dependencies, for example Guava. I reduced that number again by duplicating the used code in the `util` package instead. That was what I was alluding to.

**Comment by jcassee** [comment]
@stil4m Are you still interested in pursuing this further? "Not really" is a perfectly acceptable answer. :-)

**Comment by tubbynl** [comment]
i think we could provide the fluent api as extra API next to/reusing the current Concepts

i do think moving forward on the current codebase (not a rewrite) is required to provide a smooth migration path for current implementations to retain usage of this java client

**Comment by stil4m** [comment]
I agree with that the fluent api can act as an additional API.
Feel free to create small incremental changes, there are very good thing in the original PR.
